var R=require("../../../../chunks/ssr/[turbopack]_runtime.js")("server/app/(student)/student/profile/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__0r3y7rb._.js")
R.c("server/chunks/ssr/1lt1_next_dist_1gpo_ce._.js")
R.c("server/chunks/ssr/1lt1_next_dist_esm_build_templates_app-page_1yhfbej.js")
R.c("server/chunks/ssr/1lt1_next_dist_0g6tlov._.js")
R.c("server/chunks/ssr/[root-of-the-server]__1byvazz._.js")
R.c("server/chunks/ssr/1lt1_next_dist_14os6ye._.js")
R.c("server/chunks/ssr/1lt1_next_dist_compiled_@opentelemetry_api_index_160h88l.js")
R.c("server/chunks/ssr/[root-of-the-server]__063ve-s._.js")
R.c("server/chunks/ssr/1lt1_next_dist_client_components_1frzroc._.js")
R.c("server/chunks/ssr/1lt1_next_dist_client_components_builtin_forbidden_1qi7_eq.js")
R.c("server/chunks/ssr/1lt1_next_dist_client_components_builtin_unauthorized_1gnm_hy.js")
R.c("server/chunks/ssr/1lt1_next_dist_client_components_builtin_global-error_17dp2ed.js")
R.c("server/chunks/ssr/ai-private-tutor_src_app_(student)_layout_tsx_0jsiiek._.js")
R.c("server/chunks/ssr/0dwo__next-internal_server_app_(student)_student_profile_page_actions_14kkm4d.js")
R.m(73274)
module.exports=R.m(73274).exports
