// AUTO-GENERATED by scripts/extract-prosem.py — do not edit by hand
import type { ProsemPlan } from "@/lib/prosem";

import vii_bahasa_indonesia_ganjil from "./prosem/vii_bahasa_indonesia_ganjil.json";
import vii_bahasa_mandarin_ganjil from "./prosem/vii_bahasa_mandarin_ganjil.json";
import vii_biologi_ganjil from "./prosem/vii_biologi_ganjil.json";
import vii_biologi_genap from "./prosem/vii_biologi_genap.json";
import vii_fisika_ganjil from "./prosem/vii_fisika_ganjil.json";
import vii_informatika_ganjil from "./prosem/vii_informatika_ganjil.json";
import vii_pendidikan_pancasila_ganjil from "./prosem/vii_pendidikan_pancasila_ganjil.json";
import vii_sejarah_ganjil from "./prosem/vii_sejarah_ganjil.json";
import xi_bahasa_indonesia_ganjil from "./prosem/xi_bahasa_indonesia_ganjil.json";
import xi_bahasa_indonesia_genap from "./prosem/xi_bahasa_indonesia_genap.json";
import xi_biologi_ganjil from "./prosem/xi_biologi_ganjil.json";
import xi_fisika_ganjil from "./prosem/xi_fisika_ganjil.json";
import xi_kimia_ganjil from "./prosem/xi_kimia_ganjil.json";
import xi_matematika_ganjil from "./prosem/xi_matematika_ganjil.json";
import xi_matematika_penalaran_ganjil from "./prosem/xi_matematika_penalaran_ganjil.json";
import xi_matematika_tingkat_lanjut_ganjil from "./prosem/xi_matematika_tingkat_lanjut_ganjil.json";
import xi_sejarah_ganjil from "./prosem/xi_sejarah_ganjil.json";

/** All extracted prosem (program semester) plans. */
export const PROSEM_PLANS: ProsemPlan[] = [
  vii_bahasa_indonesia_ganjil,
  vii_bahasa_mandarin_ganjil,
  vii_biologi_ganjil,
  vii_biologi_genap,
  vii_fisika_ganjil,
  vii_informatika_ganjil,
  vii_pendidikan_pancasila_ganjil,
  vii_sejarah_ganjil,
  xi_bahasa_indonesia_ganjil,
  xi_bahasa_indonesia_genap,
  xi_biologi_ganjil,
  xi_fisika_ganjil,
  xi_kimia_ganjil,
  xi_matematika_ganjil,
  xi_matematika_penalaran_ganjil,
  xi_matematika_tingkat_lanjut_ganjil,
  xi_sejarah_ganjil,
];
